config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :superpowers, only: [] do
    resources :reviews, only: [:edit, :update, :destroy]
  end

  namespace :admin do
    resources :users
    resources :superpowers
    root "homepages#index"
    get "*path", to: "homepages#index"
  end

  namespace :api do
    namespace :v1 do
      resources :superpowers, only: [:index, :show] do
        resources :reviews, only: [:create]
      end
    end
  end

  root 'homes#index'
  get "*path", to: "homes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :review

  validates :review, uniqueness: { scope: :user }
  validates :user, uniqueness: { scope: :review }
end

app/controllers/admin/homepages_controller.rb
class Admin::HomepagesController < ApplicationController
  def index
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController

  def create
    superpower = Superpower.find(params[:superpower_id])
    parsed_review = JSON.parse(request.body.read)
    review = Review.new(rating: parsed_review["rating"], body: parsed_review["body"])
    review.user = current_user
    review.superpower = superpower

    if current_user.nil?
      render status: 401
    elsif review.save
      flash[:notice] = 'Review Added Successfully'
      render json: superpower.reviews
    else
      flash[:alert] = review.errors.full_messages.join(", ")
      render json: superpower.reviews
    end
  end
end

app/controllers/api/v1/superpowers_controller.rb
class Api::V1::SuperpowersController < ApplicationController

  def index
    render json: Superpower.all
  end

  def show
    @superpower = Superpower.find(params[:id])
    render json: {
      superpower: @superpower,
      reviews: @superpowers.reviews
    }
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize_user?, only: [:edit, :update, :destroy]

  def edit
    @review = Review.find(params[:id])
    @superpower = @review.superpower
  end

  def update
    @review = Review.find(params[:id])
    @superpower = @review.superpower

    if @review.update_attributes(review_params)
      flash[:notice] = 'Review Updated Successfully'
      redirect_to "/superpowers/#{@superpower.id}"
    else
      flash[:alert] = @review.errors.full_messages.join(", ")
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @superpower = @review.superpower

    @review.destroy

    flash[:notice] = 'Review deleted'

    redirect_to "/superpowers/#{@superpower.id}"
  end

  private

  def authorize_user?
     @review = Review.find(params[:id])
     @superpower = @review.superpower

    if !user_signed_in? || current_user != @review.user
      flash[:notice] = 'Unauthorized access'
      redirect_to new_user_session_path and return
    end
  end

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    @vote = Vote.new
    @vote.review = @review
    @vote.user = current_user
    @superpower = @review.superpower
    @reviews = @superpower.reviews


    if !@vote.save
      flash[:alert] = "You can only vote once!"
    end
  end

  def destroy
    if Vote.count > 0
      @vote = Vote.last
      @vote.destroy
    end
  end
  

  private
    def secure_params
      params.require(:vote).permit(:review, :user)
    end
    #need to pass this in to making a new Vote, after building a form submit button. Where does react come into play?
end

app/views/admin/homepages/index.html.erb
<div class="admin-text-container">
  <h1 class='admin-h1'>You are an administrator</h1>
  <h3 class='admin-h3'>With great power, comes great responsibility</h3>
</div>

<div class="admin-links">
  <div class="user-link"><%= link_to 'Users', admin_users_path %></div>
  <div class="power-link"><%= link_to 'Superpowers', admin_superpowers_path %></div>
</div>

app/views/admin/superpowers/index.html.erb
<h2 class="ru">Superpower Master List</h2>
<%if !current_user.nil? && current_user.admin? %>
<div class="add-power">
  <%= link_to "Add new superpower", new_admin_superpower_path %>
</div>
<div class="admin-panel">
  <% end %>
  <table class="table">
    <tr>
      <th>Superpower</th>
      <th>Action</th>
    </tr>
      <% @superpowers.each do |superpower| %>
        <tr>
          <td>
            <%= link_to superpower.name, admin_superpower_path(superpower.id) %>
          </td>
          <td>
            <%= link_to 'Edit', edit_admin_superpower_path(superpower) %>
          </td>
          <td>
            <%= link_to 'Delete', [:admin, superpower], method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </table>

</div>

app/views/admin/superpowers/show.html.erb
<div class="panel admin-panel">
  <h2><%=@superpower.name%></h2>
  <%=@superpower.description%>
</div>

<div class="admin-button-group">
  <%if !current_user.nil? && current_user.admin? %>
    <div class="button admin">
      <%= link_to 'Edit', edit_admin_superpower_path(@superpower) %>
    </div>
    <div class="button admin">
      <%= link_to 'Delete', [:admin, @superpower], method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <%end%>

  <div class="button admin">
    <%= link_to 'View all superpowers', admin_superpowers_path %>
  </div>
</div>

app/views/admin/users/index.html.erb
<h2 class="ru">Registered Users</h2>

<div class="admin-panel">
    <table class="table">
      <tr>
        <th>User Email</th>
        <th>Role</th>
        <th>Action</th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.role %></td>
          <td><%= link_to 'Delete', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end%>
    </table>
</div>

app/views/homes/index.html.erb
<div id="app"></div>
<%= javascript_pack_tag 'application' %>
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperpowerReviewSite</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    @import url('https://fonts.googleapis.com/css?family=Ubuntu');
  </style>
  <style>
    @import url('https://fonts.googleapis.com/css?family=Bangers');
    </style>
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>
    <section class="top-bar-section">
    <nav class="nav-container">
      <div class="nav-name">
        <%= link_to image_tag("nav-title-bar", alt: "title"), root_path %>
      </div>
      <div class="nav-logo">
        <%= link_to image_tag("SupLogo", alt: "logo"), root_path %>
      </div>
      <div class="nav-links">
        <%- if current_user -%>
          <% if current_user.admin? %>
            <div class="nav-admin"><%= link_to 'Admin', admin_root_path %></div>
          <% end %>
          <div class="nav-so"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></div>
        <%- else -%>
          <div class="nav-su"><%= link_to 'Sign Up', new_user_registration_path %></div>
          <div class="nav-si"><%= link_to 'Sign In', new_user_session_path %></div>
        <%- end -%>
      </div>
    </nav>
  </section>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/superpowers/_form.html.erb
<%= form_for @superpower do |f| %>

<% if @superpower.errors.size > 0 %>
  <ul>
    <% @superpower.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div>
  <%= f.label :name, 'Superpower'%>
  <%= f.text_area :name %>
</div>

<div>
  <%= f.label :description, 'Description' %>
  <%= f.text_area :description %>
</div>

  <%= f.submit 'Add Superpower' %>

<% end %>